### ISSUE TITLE
mup2argmap output often mangled

### ISSUE THREAD

**Issue by s6mike** [s6mike/argmap#14]
e.g.

lua mup2argmap examples/example.mup > Output/example.yml

creates:

``` yaml
---
? |
  Brunellus is irrational
: o1:
    ? |
      Brunellus studied in Paris.
    : []
    ? |
      -Most who study in Paris are rational.
    : []
  r2:
    ? |
      Brunellus is a donkey.
    : []
    ? |
      All donkeys are irrational.
    : []
...
```

When pre-existing example is:

```yaml
"Brunellus is irrational":
  r1:
    "Brunellus is a donkey.":
    "All donkeys are irrational.":
  o1:
    "Brunellus studied in Paris.":
    "-Most who study in Paris are rational.":
```

**Comment by s6mike** [comment]
`lua mup2argmap Output/Example1_ClearlyFalse_WhiteSwan_simplified.mup > Output/Example1_ClearlyFalse_WhiteSwan_simplified_roundtrip.yml ` works fine:

``` yaml
---
All swans are white.:
  r1:
    These swans are representative of all swans.: []
    Every swan I’ve ever seen is white.: []
  o2:
    Not all swans are white.: []
...

```
